### PR TITLE
use correct geocoordinates

### PR DESCRIPTION
**Pull request by cko**

### CODE REVIEW

**Comment by stockc** [comment]
Have you tried it with harp compile? It does not show the map. With harp server everything works?

**Comment by cko** [comment]
Locally it works for me with `harp server` as well as `harp compile`

```
cd mnug
harp server -p 8000
```

```
cd mnug
harp compile
cd www/
python -m SimpleHTTPServer
```

In bot cases the map at http://localhost:8000/next_meetup.html is shown in Firefox and Chrome.
I'm using node 0.12.7 with harp 0.17.0

It seems that in the meantime e6c56c1304f6a6e3f359901a13f9d781bc8906b2 was deployed to http://www.mnug.de there the map at http://www.mnug.de/next_meetup.html is visible for me in Chrome/Firefox/Jolla as well.

Could you describe your setup a bit more detailed?

**Comment by stockc** [comment]
Problem vanished. Coordinates match. Thanks for the effort!

**Comment by cko** [comment]
:smiley:

**Pull request merged**
